[project]
name = "vim_enhanced"
version = "0.1.0"
authors = ["vim_enhanced contributors"]
target = "xlam"

[src]
Chunk = "src/classes/Chunk.cls"
Config = "src/classes/Config.cls"
DblCircList = "src/classes/DblCircList.cls"
FontColor = "src/classes/FontColor.cls"
Help = "src/classes/Help.cls"
KeymapManager = "src/classes/KeymapManager.cls"
Message = "src/classes/Message.cls"
ModeNormal = "src/classes/ModeNormal.cls"
Modes = "src/classes/Modes.cls"
ModeShapeInsert = "src/classes/ModeShapeInsert.cls"
ModeVisual = "src/classes/ModeVisual.cls"
UFKeyReceiver = "src/classes/UFKeyReceiver.cls"
Vars = "src/classes/Vars.cls"
Vim = "src/classes/Vim.cls"
Common = "src/core/Common.bas"
Constants = "src/core/Constants.bas"
Core = "src/core/Core.bas"
KeyStroke = "src/core/KeyStroke.bas"
Mapping = "src/core/Mapping.bas"
Util = "src/core/Util.bas"
DefaultConfig = "src/DefaultConfig.bas"
Auxiliary = "src/functions/Auxiliary.bas"
Border = "src/functions/Border.bas"
Cell = "src/functions/Cell.bas"
Column = "src/functions/Column.bas"
Comment = "src/functions/Comment.bas"
Find_Replace = "src/functions/Find_Replace.bas"
Font = "src/functions/Font.bas"
InsertMode = "src/functions/InsertMode.bas"
Mode = "src/functions/Mode.bas"
Moving = "src/functions/Moving.bas"
Paste = "src/functions/Paste.bas"
Row = "src/functions/Row.bas"
Scrolling = "src/functions/Scrolling.bas"
Shapes = "src/functions/Shapes.bas"
Sheets = "src/functions/Sheets.bas"
Test = "src/functions/Test.bas"
UsefulCmd = "src/functions/UsefulCmd.bas"
WBFunc = "src/functions/WBFunc.bas"
Cmd = { path = "src/userforms/Cmd.frm", binary = "src/userforms/Cmd.frx" }
CmdLine = { path = "src/userforms/CmdLine.frm", binary = "src/userforms/CmdLine.frx" }
ColorPicker = { path = "src/userforms/ColorPicker.frm", binary = "src/userforms/ColorPicker.frx" }
SheetPicker = { path = "src/userforms/SheetPicker.frm", binary = "src/userforms/SheetPicker.frx" }
ThisWorkbook = "src/workbook/ThisWorkbook.cls"
